---
language: objective-c

before_install:
- git submodule update --init --recursive

script:
 - xctool -project DTRichTextEditor.xcodeproj -scheme "DTRichTextEditor (iOS)" build  -sdk iphonesimulator8.1 -arch x86_64
 - xctool -project DTRichTextEditor.xcodeproj -scheme "Demo App" build -sdk iphonesimulator8.1 -arch x86_64
 - appledoc -o /tmp .
