---
language: objective-c

before_install:
- git submodule update --init --recursive

script:
 - xctool -project DTRichTextEditor.xcodeproj -scheme "Demo App" build -sdk iphonesimulator
 - xctool -project DTRichTextEditor.xcodeproj -scheme "DTRichTextEditor (iOS)" build -sdk iphonesimulator
 - appledoc -o /tmp .
