---
#osx_image: xcode6.4
language: objective-c

env:
  - TERM=dumb
	
before_install:
	- git submodule update --init --recursive

branches:
	only:
		- develop

script:
	- ./gradlew DemoApp
	- ./gradlew DTRichTextEditor
	- ./gradlew appledoc
	- ./gradlew documentationUpload -PuploadUser=$FTP_USER -PuploadPassword=$FTP_PASSWORD