---
#osx_image: xcode6.4
language: objective-c


before_install:
	- git submodule update --init --recursive

env:
  - TERM=dumb

script:
	- ./gradlew DemoApp
	- ./gradlew DTRichTextEditor
	- ./gradlew appledoc -P$TRAVIS_BRANCH
	- ./gradlew documentationUpload -PuploadUser=$FTP_USER -PuploadPassword=$FTP_PASSWORD -P$TRAVIS_BRANCH