---
#osx_image: xcode6.4
language: objective-c


before_install:
	- git submodule update --init --recursive

branches:
	only:
		- develop

script:
	- TERM=dumb./gradlew DemoApp
	- TERM=dumb ./gradlew DTRichTextEditor
	- TERM=dumb ./gradlew appledoc
	- TERM=dumb ./gradlew documentationUpload -PuploadUser=$FTP_USER -PuploadPassword=$FTP_PASSWORD