---
language: objective-c

install: 
 - sudo easy_install cpp-coveralls

script:
 - xctool -project DTRichTextEditor.xcodeproj -scheme "Demo App" build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
 - xctool -project DTRichTextEditor.xcodeproj -scheme "DTRichTextEditor (iOS)" test -sdk iphonesimulator
 - appledoc -o /tmp .

after_success:
  - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals
